# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-11 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
