# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-11 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200411_0237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscribers',
        ),
    ]
