# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200411_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_id',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
