# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscriber_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='stripe_id',
            new_name='stripe_cus_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='stripe_sub_id',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
