# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200413_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='image_cover',
        ),
        migrations.AddField(
            model_name='video',
            name='image_landscape',
            field=models.ImageField(default=1, upload_to='media/img'),
            preserve_default=False,
        ),
    ]
