# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200414_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.BooleanField(default=0),
        ),
    ]
