# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='featured',
            field=models.BooleanField(),
        ),
    ]
