# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200414_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_cover',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_landscape',
            field=models.ImageField(upload_to='img'),
        ),
    ]
