# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200414_0313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='genre',
        ),
    ]
