# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-26 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0010_auto_20200424_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='image_cover',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_landscape',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AddField(
            model_name='watching',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Video'),
        ),
        migrations.AddField(
            model_name='watching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watched',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Video'),
        ),
        migrations.AddField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
