# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-26 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200426_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
